### ISSUE TITLE
Debug log of the MAPF planner

### ISSUE THREAD

**Issue by r06921017** [MAPF-Competition/Start-Kit#14]
I tried to run the start-kit with the problem file "random-32-32-20_even_20_problem.json" in the "benchmark_problems" directory with 100 tasks. However, the log in the terminal mentions only 97 tasks are completed instead of 100.
The exact log in the last line shows "97 tasks has been finished by far in total".

**Comment by HanZhang39** [comment]
It seems that these two are consistent with each other. Do you think there is anything wrong?

**Comment by nobodyczcz** [comment]
Is this issue gone? @r06921017

**Comment by r06921017** [comment]
Since we are using different set of benchmark, I guess this is no longer an issue.
