### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#19]
The Prepare_Your_Planner.md is missing necessary instructions/API documents:

- ~~SharedEnvironment AP~~
- ~~How to read the map~~
- Coordination system of the map: define (0,0), (x,y)->(row, columns)
- ~~Meaning of Action enum~~
- ~~Definition of orientation~~
- ~~How to read the current state of an agent.~~
- ~~State API~~
- ~~How to read the tasks for agents.~~
- ~~What should be written to Actions in the plan function call, e.g. requirement of the size of the vector<Action>~~

**Comment by YueZhang-studyuse** [comment]
Add contents v1.0 for them in develop branch.

**Comment by nobodyczcz** [comment]
Extra comment: 
- What is the plan time limit for each plan function call (emphasis on the plan time limit is a soft limit, exceeding the time limit will cause waits  for all agents in current timestep)

**Comment by YueZhang-studyuse** [comment]
add and push in develop branch

**Comment by YueZhang-studyuse** [comment]
add the descriptions of the third one (coordination) in latest commit 94da177712f3f0165777587028757699226de64b.
