### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/Start-Kit#23]
File "Prepare Your Planner.md" repeats instructions from README.md. Suggest to remove the parts about downloading the start-kit and compiling. The instructions in this document should focus only on the task at hand (i.e., planner integration)

**Comment by nobodyczcz** [comment]
### Input_output_format.md:

Need some introduction on the top of the file to explain the purpose of the file. e.g.: 

- to run the program you nend ... ... , 
- tell input/output files for evaluation, 
- tell problem specification files ... ...

**Comment by nobodyczcz** [comment]
clear explanation of files, e.g.:

- Input/output JSON file -> input/output problem file in JSON format.
- Clarify the evaluation mode.
- ... ...

**Comment by dharabor** [comment]
s/agent/robot throughout the documentation

**Comment by YueZhang-studyuse** [comment]
update the above changes in develop branch

**Comment by YueZhang-studyuse** [comment]
I also finish docx version of all the documents in start-kit in google drive under Documenttation/Start-kit documents folder (https://drive.google.com/drive/u/0/folders/1C2OyuGWiPsjU04Vlq_okpE20J2PMXvP0) in case it is easier to make changes in meeting or offline. Feel free to change it and let me know (maybe better to use another color to indicate changes), I'll put the changes back to the markdown.

**Comment by YueZhang-studyuse** [comment]
I also add more descriptions of taskAssignmentStrategy, and push to develop branch (e471fef1cc76d20aa9a8391486c62bdb476ba0d1)
