### ISSUE TITLE
Merge the src/driver.cpp and python/py_driver.cpp

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#25]
Merge these two files, to remove unnecessary duplicated codes in two files.

At the same time, we want to decouple codes in driver.cpp, make driver.cpp clean and short. So that, we can create variations of executables (e.g. a separate plan validator executable) easier, without duplicated codes shown in multiple executable entrance files (avoid changing one functionality need to change the same code at several places.)

**Comment by GreatenAnoymous** [comment]
I merged py_driver.cpp and driver.cpp in the "merge_driver" branch.
