### ISSUE TITLE
Bug on moving to the outside of the map.

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#29]
As reported in our discord: https://drive.google.com/file/d/12n1ZeI4z2zXSNcfhpjaebZAkVkQNCyt0/view?usp=sharing , the start-kit does not check whether the returned action lead agents moving to the outside of the map.

**Comment by nobodyczcz** [comment]
I double-checked the issue. The screenshot gives a different issue. But I can confirm that the start-kit does not check whether an action leads to the outside of the map.

**Comment by YueZhang-studyuse** [comment]
fix in the new push in develop branch
