### ISSUE TITLE
Optional outputs for visualiser

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#32]
Having a flag in the command line that the output json do not include things for visualizer

**Comment by YueZhang-studyuse** [comment]
update in commit 364fd4b3a2d91592bf8fa0a141dd67b051331902 in develop branch. Add options to chose (=1 show all, =2 show basic info and path related, =3 show only basic info)

**Comment by YueZhang-studyuse** [comment]
for level 2- reduce some things

**Comment by YueZhang-studyuse** [comment]
closed with commit 4d9acab662b6170846b73d49629943238fa8d7b2
