### ISSUE TITLE
Python usage issue from user feedback

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#41]
Hi @GreatenAnoymous,

A participant tried to use the Python binding and load the map in jupyter notebook using the Grid interface. But somehow the Python kernel crashed: https://media.discordapp.net/attachments/1126422589280104488/1156900303862509599/Screenshot_2023-09-28_at_11.26.48.png?ex=65174f9e&is=6515fe1e&hm=10c0b58bed5e3b52dc0a6c0084742ba3b444db42eebd3b58e97de194bfd66d65&=&width=2334&height=1424 

It would be great if you had time to check what happened here.

**Comment by GreatenAnoymous** [comment]
I could not reproduce the error on my side. I loaded all the maps without any crashes. 
![image](https://github.com/MAPF-Competition/Start-Kit/assets/18308910/853c0c75-f35b-4470-8513-4f38e9219651))

**Comment by nobodyczcz** [comment]
Could not reproduce.
