### ISSUE TITLE
Version 1.1.4 logger-related crash

### ISSUE THREAD

**Issue by sprkrd** [MAPF-Competition/Start-Kit#48]
Version 1.1.4 seems to crash immediately after trying to schedule the when calling the planner for the first time. Seems to be a threading-related issue. With CMAKE_BUILD_TYPE=DEBUG I get the following error:

`lifelong: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>; typename boost::detail::sp_member_access<T>::type = boost::log::v2_mt_posix::sinks::synchronous_sink<boost::log::v2_mt_posix::sinks::text_file_backend>*]: Assertion 'px != 0' failed.`

**Comment by nobodyczcz** [comment]
Hi @sprkrd, 

Thanks for the issue report. Sorry for the inconvenience caused by the bug. It looks like the issue is with the logger, the logger sink ptr initialization crashed here.

Fortunately, the issue will not crush release evaluation, you still can evaluate the code under release mode. We will post a fix to the issue as soon as possible.

Best,
Zhe

**Comment by nobodyczcz** [comment]
Hi @sprkrd,

I failed to reproduce the error here. Could you give me more information on your operating platform and the version of boost installed on your machine?

Best,
Zhe

**Comment by sprkrd** [comment]
> Hi @sprkrd,
> 
> Thanks for the issue report. Sorry for the inconvenience caused by the bug. It looks like the issue is with the logger, the logger sink ptr initialization crashed here.
> 
> Fortunately, the issue will not crush release evaluation, you still can evaluate the code under release mode. We will post a fix to the issue as soon as possible.
> 
> Best, Zhe

Hi @nobodyczcz . Sorry, I wasn't clear enough. The program still crashes in release mode with a segmentation fault. It's just that I get a more descriptive error message when I enable debug mode.

> Hi @sprkrd,
> 
> I failed to reproduce the error here. Could you give me more information on your operating platform and the version of boost installed on your machine?
> 
> Best, Zhe

My Boost version is 1.71, and I work with a Ubuntu 20.04 distribution. So far I've got the same error in two different machines, the other one being Ubuntu 18.04 (I do not know the Boost version of the other one).

I'll see if I can put together a minimum working example of code that triggers the bug.

**Comment by sprkrd** [comment]
Following up on my previous comment: the basic start kit as is, i.e. with no modifications from me, triggers the error.

**Comment by nobodyczcz** [comment]
Hi @sprkrd , thanks for the details. Could you verify on your machine by replacing line 22 of Logger.h (    boost::shared_ptr<boost::log::sinks::synchronous_sink<boost::log::sinks::text_file_backend>> sink;
) with

```
    boost::shared_ptr<boost::log::sinks::synchronous_sink<boost::log::sinks::text_file_backend>> sink;
```
will the issue be fixed?

Thanks!

**Comment by nobodyczcz** [comment]
> Following up on my previous comment: the basic start kit as is, i.e. with no modifications from me, triggers the error. This is the line I use to test the lifelong executable:
> 
> `./lifelong --inputFile ../example_problems/warehouse.domain/warehouse_small_100.json -o test.json --planTimeLimit 1`

Oh, thanks for the example. I can reproduce the issue with this configuration now.

**Comment by sprkrd** [comment]
Hello @nobodyczcz. No, it is not fixed. However, I believe I have found the problem. The sink shared_ptr is not set at any moment. There's no check to see if sink is null when the flush method is called, and this is when the program crashes. Probably you were not able to reproduce the error because you were providing a log file. Something like:

`./lifelong  --inputFile ../example_problems/warehouse.domain/warehouse_small_100.json -o test.json --planTimeLimit 1 -l logFile.txt`

Since, on the other hand, there are checks to see if the logger pointer of the CompetitionSystem classes is nullptr. Thus, I believe a simple fix could be to replace lines 78-80 of driver.cpp with the following:

```
     Logger *logger = nullptr;
     if (vm.count("logFile"))
     {   
         logger = new Logger();
         logger->set_logfile(vm["logFile"].as<std::string>());
     } 
```
With this, there are no errors anymore even if I don't specify a logger. I believe this is more flexible in case the user doesn't want to provide a logger. I'll see to do a pull request with this modification.

**Comment by nobodyczcz** [comment]
> Hello @nobodyczcz. No, it is not fixed. However, I believe I have found the problem. The sink shared_ptr is not set at any moment. There's no check to see if sink is null when the flush method is called, and this is when the program crashes. Indeed, this error disappears when a log file is provided. Something like:
> 
> `./lifelong --inputFile ../example_problems/warehouse.domain/warehouse_small_100.json -o test.json --planTimeLimit 1 -l logFile.txt`
> 
> On the other hand, there are checks to see if the logger pointer of the CompetitionSystem classes is nullptr. Thus, I believe a simple fix could be to replace lines 78-80 of driver.cpp with the following:
> 
> ```
>      Logger *logger = nullptr;
>      if (vm.count("logFile"))
>      {   
>          logger = new Logger();
>          logger->set_logfile(vm["logFile"].as<std::string>());
>      } 
> ```
> 
> With this, there are no errors anymore even if I don't specify a logger. I believe this is more flexible in case the user doesn't want to provide a logger. I'll see to do a pull request with this modification.

Hi @sprkrd , yes, I located the same place. I'll push a emergency fix now.
