### ISSUE TITLE
Refactor simulator as component of CompetitionSystem.

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#56]
- Currently, the simulation is happening across the class ActionModel and CompetitionSystem, 
- we need to unify these functionalities into a single simulator class with a generic interface
- so that we can implement different simulators with different agent models. e.g., MAPF, MAPF_R, Real robots ... ....  related to: https://github.com/MAPF-Competition/Start-Kit/issues/35

**Comment by dharabor** [comment]
Yue, can you please comment on how the recent refactorings bear on this issue? @YueZhang-studyuse
