### ISSUE TITLE
Output Change for 2024

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/Start-Kit#57]
For the task schedule, we need to change the output to also record the task schedule for each time step.
Previous output:
{  
    "actionModel": "MAPF",
    "AllValid": ,
    "teamSize": ,
    “Start”:[],
    “numTaskFinished”:,
    “Makespan”:,
    “actualPahts”:[],
    “plannerPaths”:[],
    “plannerTimes”:[],
    “Errors”:[],  – errors
    “Events”:[],  – task released, task assignment, task finished
    “Tasks”:[]   – task pool <id,loc>
}

Proposed output:
{  
    "actionModel": "MAPF",
    "AllValid": ,
    "teamSize": ,
    “Start”:[],
    “numTaskFinished”:,
    “Makespan”:,
    “actualPaths”:[],
    “plannerPaths”:[],
    “plannerTimes”:[],
    “Errors”:[]

    //changes for 2024
   “ScheduleErrors”: [] - task errors, i.e., task_id, agent_id for previous assignment, agent_id for proposed assignment, timestep, error type
    “Events”:[],  –  task finished (same as previous while removing task assignment event)
    “Tasks”:[]   – task pool   <id,release time,loc1,loc2,...> for matching task id and the location of the tasks
    “actualTaskSchedule”:[] - we only record the changes of the schedule, i.e., t1:task_id1,task_id2, t3: task_id3,task_id2
    “planTaskSchedule”:[] - we only record the changes of the schedule
}

Besides that, we also want to support simpler output, i.e., output only selected agents by specifying in command line input. For example, if you call start-kit by ./lifelong .....(other required parameters) -- outputAgents 1,3,5,6,7, then the output will only show actualPaths, plannerPaths, events, tasks, scheduleErrors, planTaskSchedule, actualTaskSchedule, errors for the selected agents, for other agents, will replaced by ','

**Comment by shchan13** [comment]
Hello, here are some issues I found while enhancing PlanViz with the new output.json...
1. Why is there multiple [0,0,0,0] events? Does that mean agent 0 finishes tasks at timestep 0?
2. Do we replace assigned events to actual schedule?
3. Confusion between events and schedules:
    a. How do we know what agent is doing what task given a timestep?
    b. Is it possible to load one section and get all the information of events?
4. A simpler example (5 agents with 10 3-location tasks) is needed for varify the new PlanViz

**Comment by dharabor** [comment]
I think the format change is done. Some documentation updates, considering Shao's comments, would be useful. Yue or Han, can you please comment.
