### ISSUE TITLE
move update_goal_locations inside scheduler->plan()?

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/Start-Kit#59]
Currently the update goal location (update goal locations in share_env with the new assignment) is in default entry. 
Since it has tiny overheads and will count for given time limit, maybe it's better to move to plan function in scheduler? 

Then we should ask participants to also implement this and inform the planner.

**Comment by dharabor** [comment]
We need an update here, @YueZhang-studyuse. Is this issue fixed? If not, is it still relevant?

**Comment by nobodyczcz** [comment]
For participants who want to modify the proposed schedule they should create an combined track entry.
