### ISSUE TITLE
Support turn costs in 2024 default planner

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/Start-Kit#60]
As previously discussed, the new default planner needs to account for turn costs. The required changes are at two levels: 

1. Expander needs to updated, to consider turn actions
2. State description needs to be updated, to add agent direction
3. Heuristic tables need to be extended, from (x, y) to (x, y, \vec{v}) where \vec{v} is a unit vector describing the agent's orientation.

**Comment by YueZhang-studyuse** [comment]
update in branch 2024develop-pibt-turn

**Comment by nobodyczcz** [comment]
comments on 2024-9-6
Test the turning implementation
-  with first come first server task assignemnt
- with minimal makespan task assignment.

**Comment by dharabor** [comment]
What's the status of this one? I think we implemented (1) and (2) but not (3), is that right? @YueZhang-studyuse

**Comment by dharabor** [comment]
I think this is done, sans heuristic. Seems to work well enough, even though the estimates are less accurate.
