### ISSUE TITLE
Default planner 2024 -- improve memory usage

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/Start-Kit#61]
We store a heuristic table for each agent. When solving large instances with many agents the total memory requirements become quite large (10+GB). 

e.g., 10K agents and 400K states per map (100K grid nodes, 4 agent directions) and 4 bytes per value, we require ~15GB. This is a lower priority for now, as the evaluation machine has 64GB of RAM.

**Comment by nobodyczcz** [comment]
Works, for current competition not an issue.
