### ISSUE TITLE
[Question] C++ & boost versions

### ISSUE THREAD

**Issue by miquelramirez** [MAPF-Competition/Start-Kit#66]
Dear MAPF-Competition team,

The provided `cmake` scripts set C++17 as the target C++ standard and require a pretty old version of `boost.` If I changed the former to C++ 20 and the latter to 1.74 (the version that ships with Ubuntu 22.04), would that cause trouble in the execution environment? 

Thank you kindly for your guidance!

**Comment by dharabor** [comment]
Thank you for raising this issue. 
In principle, I can't see a problem. But we need to test. We'll update this issue when we get more details.

**Comment by nobodyczcz** [comment]
Hi @miquelramirez, 

Sorry for the late reply. C++17 and boost 1.49.0 are just the minimal requirements. It is totally fine using C++ 20 and boost 1.74.0. Actually, the boost installed in the evaluation docker container is version 1.74.0. You can find more detailed information about the evaluation environment here: [Evaluation_Environment.md](https://github.com/MAPF-Competition/Start-Kit/blob/main/Evaluation_Environment.md)

Best,
Mike

**Comment by miquelramirez** [comment]
Thank you @nobodyczcz

**Comment by miquelramirez** [comment]
So far I have been using `boost` for some of the features of the standard library that come with C++20. But good to know.
