### ISSUE TITLE
[Question] `proposed_schedule` changing sizes

### ISSUE THREAD

**Issue by miquelramirez** [MAPF-Competition/Start-Kit#68]
Hello,

Could someone explain why the vector `proposed_schedule` changes size between ticks/frames of the simulation? 

The default planner code (`default_planner/scheduler.cpp`, line 21) has this to say

```C++
proposed_schedule.resize(env->num_of_agents, -1); //default no schedule
```

My interpretation of the comment `//default no schedule` was that agents are not assigned any tasks by default. But perhaps this means that there is literally no schedule, as in `proposed_schedule` being empty.

Thanks in advance.

**Comment by miquelramirez** [comment]
As I am getting more familiar with the code base this is becoming more clear to me. The "explanation" can be found on the loop on `BaseSystem::simulate` (file `CompetitionSystem.cpp`):

```c++

void BaseSystem::simulate(int simulation_time)
{
    //init logger
    //Logger* log = new Logger();
    initialize();

    for (; simulator.get_curr_timestep() < simulation_time; )
    {
        // find a plan
        sync_shared_env();

        auto start = std::chrono::steady_clock::now();

        vector<Action> actions;
        vector<int> proposed_schedule;
        plan(actions,proposed_schedule);

        auto end = std::chrono::steady_clock::now();

        for (int a = 0; a < num_of_agents; a++)
        {
            if (!env->goal_locations[a].empty())
                solution_costs[a]++;
        }

        // move drives
        //move(actions);
        vector<State> curr_states = simulator.move(actions);
        int timestep = simulator.get_curr_timestep();
        // agents do not move

        for (int k = 0; k < num_of_agents; k++)
        {
            paths[k].push_back(curr_states[k]);
            actual_movements[k].push_back(actions[k]);
        }
        if (!planner_movements[0].empty() && planner_movements[0].back() == Action::NA)
        {
            planner_times.back()+=plan_time_limit;  //add planning time to last record
        }
        else
        {
            auto diff = end-start;
            planner_times.push_back(std::chrono::duration<double>(diff).count());
        }

        // update tasks
        task_manager.update_tasks(curr_states, proposed_schedule, simulator.get_curr_timestep());
    }
}
```

From looking closely at the above I would suggest to proceed in the following way:

- Declare `action` and `proposed_schedule` outside of the loop. 
- Allocate the `proposed_schedule` right away on the basis of the data provided by `env`, which does not change like ever.
- The size of `actions` will vary, as it depends on the length of the plans assigned to individual agents. I would suggest to preallocate some space (via `std::vector<T>::reserve`) to something safe (like as many action elements as agents) and then invoke the method `clear` on `actions`. By doing this the allocations are amortised and only require the client to resize `actions` as necessary.
- I do not see any reason why `proposed_schedule` should be pass by value to `TaskManager::update_tasks`.

I hope this is helpful,

Miquel.

**Comment by nobodyczcz** [comment]
Hi Miquel,

Thanks for your feedback.

I reviewed the codes on this part with @YueZhang-studyuse, and we agree that there are plenty of redundant vector initialisations in the code. We plan to raise an issue and improve it by reusing initialised vectors and reserving sufficient capacity for them to avoid redundant memory allocation. 

We appreciate your valuable feedback. We are reviewing other issues as well and will get back to them one by one.

Best,
Mike

**Comment by miquelramirez** [comment]
Sounds great guys. 

I will be writing shortly about a nasty memory corruption related to the interaction between the sim and planner/scheduler when there are timeouts. 

I also have some comments/suggestions regarding the interface offered by `SharedEnvironment` to keep track of ongoing tasks.

Best,

Miquel.

**Comment by nobodyczcz** [comment]
I will raise a separate issue on what to do only.
