### ISSUE TITLE
[Suggestion] Timeout logging and notification

### ISSUE THREAD

**Issue by miquelramirez** [MAPF-Competition/Start-Kit#70]
Dear MAPF-Competition team,

on my quest to resolve the crash I mentioned on #69  I have got a better handle on the inner workings of the simulator and as a result I have some suggestions to provide clearer outputs when the planner (or some of its components) time out.

The prompt at line 67, `CompetitionSystem.cpp`

```c++
std::cout << started << "     " << (future.wait_for(std::chrono::milliseconds(0)) != std::future_status::ready) << std::endl;
``` 

was producing the rather mysterious output

```
1               1
```

The information it conveys is useful to the user... when presented with some  context. I would suggest this is prompted on the logs, along with a sequence of suitably chosen English words that explain what the condition on line 67 of `CompetitionSystem.cpp` means.

More generally, I would suggest that all logged messages appear with some context information. For instance, becoming perhaps

```c++
logger->log_info("BaseSystem::plan(): planner cannot run because the previous run is still running", timestep);
```

or something like that.

Also some of the messages seem to make unwarranted assumptions. For instance, in lines 62-69 of `TaskManager.cpp` one can find the following postcondition check

```c++
    if (! validate_task_assgnment(assignment))
    {
        if (assignment.size() < num_of_agents)
            logger->log_info("task scheduler tiemout");
        else
            logger->log_warning("attempt to set invalid task assignment");
        return false;
    }
```
Why does it follow from observing that the `assignment` vector is smaller than expected that there has been a time out of the scheduler? I am getting these messages and I know for a fact the scheduler isn't timing out, but rather `pibt` is the one timing out...

Thanks all,

Miquel.

**Comment by nobodyczcz** [comment]
moved to issue:
https://github.com/MAPF-Competition/Start-Kit/issues/82
https://github.com/MAPF-Competition/Start-Kit/issues/81
