### ISSUE TITLE
[Question] Ongoing tasks: how to abandon a task that is not open?

### ISSUE THREAD

**Issue by miquelramirez** [MAPF-Competition/Start-Kit#72]
Dear MAPF-Competition Team,

Could you please provide detailed steps for canceling an assignment (indicating the interactions between the scheduler and the environment data structure)? 

That is, say that agent $i$ got task $j$ assigned at time $t$. After some time, the scheduler changes its mind, say $t'$. The scheduler checks whether agent $i$ has completed any of the errands of task $j$. If no errand has been completed (e.g. agent $i$ hasn't gone through the first location associated with tasks $j$), what would be the scheduler code to cancel the assignment? Does the scheduler needs to wait for one tick before assigning a different task to agent $i$?

Thank you

**Comment by nobodyczcz** [comment]
Hi Miquel,

You can assign this agent another task as long as the current task is not opened. You also can exchange unopened tasks between agents.

But, currently, you cannot abandon the task without assigning the agent another task. If you think abandoning a task without assigning a new task will be useful, we could explore such option.

Best,
Mike

Best,
Mike

**Comment by miquelramirez** [comment]
Hi Mike,

Okay, that explains my issues. I will need to think carefully about the implications of that restriction.

> . If you think abandoning a task without assigning a new task will be useful, we could explore such an option.

Ideally, I would be able to create "recovery" tasks that constrain the agents' behavior. The simplest example is what you mention: "stay in place (kind of)." 

I am happy with the current challenge as it is. I just need to wrap my head around it :)

Daniel helpfully pointed me to the Discord channel - I will switch my questions there as it seems to be a more popular venue.

**Comment by nobodyczcz** [comment]
Hi Miquel,

After reviewing the code, I realised an issue with "assign an agent another task as long as the current task is not opened". If the current task is not reassigned to another agent, this task is abandoned. However, the code does not reset the task->agent_assigned in this case.

I'll raise a bug fix issue on this problem.

Best,
Mike

**Comment by miquelramirez** [comment]
:+100:
