### ISSUE TITLE
Behaviour of assignment -1 and drop assignment

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#80]
The behaviour of assignment -1 needs to be clarified, currently, -1 indicates no assignment or no changes, but it raises an invalid assignment error if an agent currently has an opened task

- Make -1 as no task
- Reset the task->agent_assigned to -1, if the task is abandoned, either because of commanded to drop (assign -1) or the agent is rescheduled to another task with the current task not rescheduled
- set -1 in proposed_schedule for agents that finish their tasks before passing it to entry.compute()
- if an agent opened a task, it cannot be set as -1

**Comment by YueZhang-studyuse** [comment]
fix in commit 1989f7bc213143c4a01ba7f7974654acf9c3ce70
