### ISSUE TITLE
Logger behavior

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#82]
- Whenever an error is recorded to output, use a logger to log them as well.
- provide a CLI argument to mute or set the log level for the logger, so that the program can run in silent mode or only log info+warning+error, or warning+error, or error only

**Comment by dharabor** [comment]
I'm not sure I understand this proposal. If there are messages going to the console, they need to get there via a logger object. Is that the idea? IMO, we should not have any output sent directly to `std::cout`, or `std::cerr`. 

Or is this message saying, any messages which are sent to the console (via the logger) should also be sent to a log file? This seems fine, provided the user specifies a log file destination and the path to that logfile is valid. 

Related to Issue#67

**Comment by nobodyczcz** [comment]
We will keep it like this for the main round of 2024 but aim for a unified logging interface subsequently.

**Comment by YueZhang-studyuse** [comment]
fix in commit 1989f7bc213143c4a01ba7f7974654acf9c3ce70
