### ISSUE TITLE
Scheduler track participants freely command agents to any location

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/Start-Kit#84]
Move set_goal_locations to scheduler

- Scheduler track participants can freely command agents to any location on the map.
- modify Python interface to allow this operation

**Comment by dharabor** [comment]
I'm not sure the scheduler should be messing with the decisions of the planner. Sounds like what we want is a new type of task; a length 1 errand that must be completed by a specific agent.

**Comment by nobodyczcz** [comment]
Had a discussion with Daniel on this problem. It's making the job of scheduler complicated and giving the job of planner partly to the scheduler. Thus decided to not do it.

But would be interesting to have some additional types of tasks in the future. Like charging task!
