### ISSUE TITLE
Addition of Moving Obstacle to the Simulator

### ISSUE THREAD

**Issue by MeetSable** [MAPF-Competition/Start-Kit#87]
**Proposal**  
The current simulator setup only accounts for static obstacles defined within the map. However, in real-world applications, unexpected obstacles can appear dynamically within open spaces. The MAPD (Multi-Agent Pathfinding with Deadlines) algorithm should be capable of handling such obstacles effectively.

**Feature Request**  
Add the functionality for moving obstacles within the simulator environment. These moving obstacles should have configurable properties to simulate real-world unpredictability.

**Proposed Implementation Details**  
1. **Control Variables**: Introduce control variables to adjust the behavior of moving obstacles.
   - **Number of Obstacles**: Specify the number of moving obstacles.
   - **Spawn/Despawn Probability**: Adjust the probability of obstacles appearing and disappearing within the map.
   - **Movement Randomness**: Set a randomness factor for the movement of obstacles within the simulation environment.

2. **Behavior of Moving Obstacles**:
   - Moving obstacles should spawn in free spaces not occupied by agents.
   - They should follow random or configurable movement patterns, with potential for collision or avoidance behaviors to mimic realistic dynamic environments.

**Additional Context**  
Adding dynamic obstacles will help in testing and validating the MAPD algorithm's robustness in realistic, unpredictable scenarios.

**Comment by dharabor** [comment]
Hi @MeetSable, 

Thank you for posting this issue. 

Regarding your first feature request, MAPD with deadlines. Currently, Robot Runners does not impose deadlines on task completions, but this is an interesting topic which has received some attention in the literature. We actually discussed it ahead of the 2024 main round but elected not to implement deadlines on this occasion, given all the other changes. That said, it could be an a good future direction for the competition -- thank you for suggesting it. We will add it to the list of things to consider when we plan the next edition.

Regarding your second feature request, moving obstacles. We do not currently have any plans to support such a variant however, if you find it interesting for your own research, it sounds like something that you might be able to implement with the existing software. In my mind, moving obstacles can be understood as higher priority agents whose paths are not controlled by the planner. One way to implement this behaviour is to create a nested planner. The outer layer plans the actions of the "moving obstacles". Then control is handed to the inner layer, which plans the actions of the other agents. I can see you have some ideas about how the moving obstacle paths should be generated. I think these could also be explored within the suggested setup (e.g., as parameters to the outer layer).

I will leave this discussion open for a bit longer, in case others want to chime in. A likely resolution at this point is that the first suggestion becomes a new issue for discussion.
